name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
            exe: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive: tar.gz
            exe: ""
          - os: macos-14
            target: aarch64-apple-darwin
            archive: tar.gz
            exe: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
            exe: ".exe"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build musl target in Alpine Docker container
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          # Create a Docker script
          cat > build-musl.sh << 'EOF'
          #!/bin/sh
          set -ex

          # Install build dependencies
          apk add --no-cache build-base curl git openssl-dev openssl-libs-static pkgconfig rust cargo

          # Clone the repository
          git clone /github/workspace /build
          cd /build

          # Build the project
          cargo build --release --target=x86_64-unknown-linux-musl

          # Copy the binary back to the workspace
          mkdir -p /github/workspace/target/x86_64-unknown-linux-musl/release/
          cp target/x86_64-unknown-linux-musl/release/av /github/workspace/target/x86_64-unknown-linux-musl/release/
          EOF

          # Make the script executable
          chmod +x build-musl.sh

          # Run the build in Alpine container
          docker run --rm -v $GITHUB_WORKSPACE:/github/workspace -w /github/workspace alpine:latest sh -c "./build-musl.sh"

      - name: Build (non-musl targets)
        if: matrix.target != 'x86_64-unknown-linux-musl'
        run: cargo build --release --target ${{ matrix.target }}

      # Build for musl target is now handled by the Alpine Docker container step

      - name: Prepare package (unix)
        if: matrix.archive == 'tar.gz'
        shell: bash
        run: |
          set -euxo pipefail
          BIN=av
          OUT_DIR=dist
          mkdir -p "$OUT_DIR"
          SRC="target/${{ matrix.target }}/release/${BIN}"
          ASSET="${BIN}-${GITHUB_REF_NAME}-${{ matrix.target }}.tar.gz"
          tar -C "target/${{ matrix.target }}/release" -czf "$OUT_DIR/$ASSET" "$BIN"

      - name: Prepare package (windows)
        if: matrix.archive == 'zip'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $Bin = 'av.exe'
          $OutDir = 'dist'
          New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
          $Src = "target/${{ matrix.target }}/release/$Bin"
          $Asset = "av-$env:GITHUB_REF_NAME-${{ matrix.target }}.zip"
          Compress-Archive -Path $Src -DestinationPath "$OutDir/$Asset"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: av-${{ github.ref_name }}-${{ matrix.target }}
          path: dist/*
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
